/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AnimateurController;
import Controller.ClasseController;
import Controller.CoursController;
import Model.Animateur;
import Model.Classe;
import Model.Cours;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mohamed
 */
public class Anim_Cours_Classe extends javax.swing.JInternalFrame {

    /**
     * Creates new form Anim_Cours_Classe
     */
    
    private DefaultTableModel model = new DefaultTableModel();
    String selectednomclasse=null;
    private String selectedcode=null; 
     String selectedcin=null;
    
    void RemoveTitleBar()
    {
        putClientProperty("acc.ispalette",Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
    
    
    public Anim_Cours_Classe() throws SQLException, ClassNotFoundException {
        initComponents();
        RemoveTitleBar();
        remplirJTable();
        remplirJTableanim();
        remplirJTableclasse();
    }
    
    
    
    
    
     private void remplirJTable() throws SQLException, ClassNotFoundException
	{ 
		model = new DefaultTableModel();
		model.addColumn("Code");
		model.addColumn("Designation");
		//model.addColumn("Animateur Responsable");
		//model.addColumn("Classe");
                model.addColumn("Prix");
		
	         CoursController cc = new CoursController();
	        ArrayList<Cours> liste = cc.listerCours();
	        for (int i=0;i<liste.size();i++)
	        {
	        Cours currentCours = liste.get(i);
	        model.addRow(new Object[]{currentCours.getCode(),
	        currentCours.getDesignation(),
	         currentCours.getPrix()
                });
	        }
	        Table.setModel(model);
	}
     
     
     private void remplirJTableanim() throws SQLException, ClassNotFoundException
	{ 
           // JCheckBox cb=new JCheckBox();
            
		model = new DefaultTableModel();
               // model.addColumn("seleciton");
		model.addColumn("CIN");
		model.addColumn("Nom");
		model.addColumn("Prenom");
		model.addColumn("Prenom_pere");
		model.addColumn("Num_tel");
            
	        AnimateurController C = new AnimateurController();
	        ArrayList<Animateur> liste = C.listerAnimateur();
	        for (int i=0;i<liste.size();i++)
	        {
	        Animateur currentAnimateur = liste.get(i);
	        model.addRow(new Object[]{currentAnimateur.getId_cin(),
	        currentAnimateur.getNom(), currentAnimateur.getPrenom(),
	        currentAnimateur.getPrenomPere(),	            
                currentAnimateur.getNum_tel(),
	        
           });
	        }
	        TableAnimateur.setModel(model);
	}
     
     private void remplirJTableclasse() throws SQLException, ClassNotFoundException
	{ 
		model = new DefaultTableModel();
		model.addColumn("Nom_Classe");		
	           ClasseController C = new ClasseController();
	        ArrayList<Classe> liste = C.listerClasse();
	        for (int i=0;i<liste.size();i++)
	        {
	        Classe currentClasse = liste.get(i);
	        model.addRow(new Object[]{currentClasse.getNomClasse(),
	        });
	        }
	        TableClasse.setModel(model);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAnimateur = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableClasse = new javax.swing.JTable();
        BtnEff = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(41, 75, 124));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Attribuer Cours");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel16)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste Des Cours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(41, 75, 124))); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        Table.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setAutoscrolls(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste Des Animateurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(41, 75, 124))); // NOI18N
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        TableAnimateur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TableAnimateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableAnimateur.setAutoscrolls(false);
        TableAnimateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAnimateurMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableAnimateur);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste Des Classes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(41, 75, 124))); // NOI18N
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        TableClasse.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TableClasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableClasse.setAutoscrolls(false);
        TableClasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClasseMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableClasse);

        BtnEff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnEff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/file.png"))); // NOI18N
        BtnEff.setText("Effctuer Animateur/Cours");
        BtnEff.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        BtnEff.setContentAreaFilled(false);
        BtnEff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEffMouseExited(evt);
            }
        });
        BtnEff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(BtnEff, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setBounds(0, 0, 1050, 621);
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:

        //Deplace();

        selectedcode= (String)Table.getValueAt(Table.getSelectedRow(),0);

    }//GEN-LAST:event_TableMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void TableAnimateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAnimateurMouseClicked
        // TODO add your handling code here:

        //Deplace();

        selectedcin= (String)TableAnimateur.getValueAt(TableAnimateur.getSelectedRow(),0);

    }//GEN-LAST:event_TableAnimateurMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void TableClasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClasseMouseClicked
        // TODO add your handling code here:

        //Deplace();

        selectednomclasse=(String)TableClasse.getValueAt(TableClasse.getSelectedRow(),
						0);

    }//GEN-LAST:event_TableClasseMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void BtnEffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEffMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEffMouseEntered

    private void BtnEffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEffMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEffMouseExited

    private void BtnEffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEffActionPerformed
        // TODO add your handling code here:

        if(selectedcode == null || selectedcin==null || selectednomclasse==null)
				{
					JOptionPane.showMessageDialog(null,
							"Veuillez selectionner une ligne !!");
				}
				else
				{
					
					try {
						CoursController cc = new CoursController();
						if(cc.eff_anim_cours_classe(selectedcin,selectedcode,selectednomclasse))
						{
							JOptionPane.showMessageDialog(null,
									" succès");
						}
					} catch (SQLException e1) {
						JOptionPane.showMessageDialog(null,
								e1.getMessage());
					} catch (ClassNotFoundException e1) {
						JOptionPane.showMessageDialog(null,
								e1.getMessage());
					}
				}
        

    }//GEN-LAST:event_BtnEffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEff;
    private javax.swing.JTable Table;
    private javax.swing.JTable TableAnimateur;
    private javax.swing.JTable TableClasse;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
